version: '3'

services:
  backend:
    image: backend
    environment:
      - FRONT_URL=http://localhost:5000  
      - REDIS=redis
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_NAME=yumodb
      - DB_HOST=db
    depends_on:
      - db
    ports:
      - 8000:8000
    container_name: backend
    command: npm start
  frontend:
    image: frontend
    environment:
      - API_URL=http://localhost:8000
    ports:
      - 5000:5000
    container_name: frontend
    command: npm start
  redis:
    image: redis
  webserver:
    image: nginx
    container_name: webserver
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports: 
      - 80:80
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
  db:
     image: postgres
     restart: unless-stopped
     environment: 
       POSTGRES_USER: user
       POSTGRES_PASSWORD: password
       POSTGRES_DB: yumodb
     container_name: db

   
